# Desk Box-only rebuild profile.
#
# Columns:
# 1.ID  2.MODEL  3.SOC  4.FDTFILE  5.TRUST_IMG  6.MAINLINE_UBOOT
# 7.BOOTLOADER_IMG  8.DESCRIPTION  9.KERNEL_TAGS  10.PLATFORM  11.FAMILY
# 12.BOOT_CONF  13.CONTRIBUTORS  14.BOARD  15.BUILD

r709:Desk Box:rk3528:rk3528-deskbox.dtb:NA:NA:bootloader.bin:4GB-Mem,32GB-eMMC,TF,AIC8800D80-WiFi:rk35xx/6.1.y:rockchip:rk3528:armbianEnv.txt:hudrucan:deskbox:yes
